"""initial schema

Revision ID: 067a98d3ecaf
Revises: 0001_enable_pgvector
Create Date: 2026-04-22 02:41:23.545533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '067a98d3ecaf'
down_revision: Union[str, Sequence[str], None] = '0001_enable_pgvector'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=10), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('relative_path', sa.String(length=1024), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('blurhash', sa.String(length=64), nullable=True),
    sa.Column('thumbnail_status', sa.String(length=20), nullable=False),
    sa.Column('sort_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    # FK assets.pack_id -> packs.id 延后到 create_foreign_key，
    # 避免 assets ↔ packs 之间的循环依赖导致 create_table 报错
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('root_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_candidates', sa.Integer(), nullable=False),
    sa.Column('imported_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('dir_path', sa.String(length=1024), nullable=False),
    sa.Column('original_folder_name', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cover_asset_id', sa.Integer(), nullable=True),
    sa.Column('photo_count', sa.Integer(), nullable=False),
    sa.Column('video_count', sa.Integer(), nullable=False),
    sa.Column('total_size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cover_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('tag_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'work_id', name='uq_character_name_work')
    )
    op.create_table('cosers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('avatar_asset_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['avatar_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('import_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('folder_path', sa.String(length=1024), nullable=False),
    sa.Column('folder_name', sa.String(length=512), nullable=False),
    sa.Column('detected_title', sa.String(length=512), nullable=True),
    sa.Column('detected_coser_names', sa.String(length=512), nullable=True),
    sa.Column('detected_work_name', sa.String(length=256), nullable=True),
    sa.Column('detected_character_names', sa.String(length=512), nullable=True),
    sa.Column('photo_count', sa.Integer(), nullable=False),
    sa.Column('video_count', sa.Integer(), nullable=False),
    sa.Column('total_size_bytes', sa.Integer(), nullable=False),
    sa.Column('existing_pack_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metadata_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('candidate_value', sa.String(length=512), nullable=False),
    sa.Column('candidate_entity_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['packs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pack_tag',
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['packs.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('pack_id', 'tag_id')
    )
    op.create_table('coser_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coser_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['coser_id'], ['cosers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_table('outfits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'character_id', name='uq_outfit_name_character')
    )
    op.create_table('pack_character',
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['pack_id'], ['packs.id'], ),
    sa.PrimaryKeyConstraint('pack_id', 'character_id')
    )
    op.create_table('pack_coser',
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('coser_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['coser_id'], ['cosers.id'], ),
    sa.ForeignKeyConstraint(['pack_id'], ['packs.id'], ),
    sa.PrimaryKeyConstraint('pack_id', 'coser_id')
    )
    op.create_table('pack_outfit',
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('outfit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ),
    sa.ForeignKeyConstraint(['pack_id'], ['packs.id'], ),
    sa.PrimaryKeyConstraint('pack_id', 'outfit_id')
    )
    op.create_foreign_key(
        'fk_assets_pack_id',
        'assets',
        'packs',
        ['pack_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_assets_pack_id', 'assets', type_='foreignkey')
    op.drop_table('pack_outfit')
    op.drop_table('pack_coser')
    op.drop_table('pack_character')
    op.drop_table('outfits')
    op.drop_table('coser_aliases')
    op.drop_table('pack_tag')
    op.drop_table('metadata_suggestions')
    op.drop_table('import_candidates')
    op.drop_table('cosers')
    op.drop_table('characters')
    op.drop_table('works')
    op.drop_table('tasks')
    op.drop_table('tags')
    op.drop_table('packs')
    op.drop_table('import_batches')
    op.drop_table('assets')
    # ### end Alembic commands ###
